-- MySQL Script generated by MySQL Workbench
-- Thu May  2 21:44:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema E_tiketing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema E_tiketing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `E_tiketing` DEFAULT CHARACTER SET utf8 ;
USE `E_tiketing` ;

-- -----------------------------------------------------
-- Table `E_tiketing`.`Akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_tiketing`.`Akun` (
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` INT NOT NULL,
  PRIMARY KEY (`Username`));
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `E_tiketing`.`Mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_tiketing`.`Mahasiswa` (
  `NIM` INT NOT NULL,
  `Nama` VARCHAR(100) NULL,
  `Prodi` VARCHAR(30) NULL,
  `Username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIM`),
  INDEX `fk_Mahasiswa_Akun1_idx` (`Username` ASC),
  CONSTRAINT `fk_Mahasiswa_Akun1`
    FOREIGN KEY (`Username`)
    REFERENCES `E_tiketing`.`Akun` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `E_tiketing`.`Acara`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_tiketing`.`Acara` (
  `KodeAcara` INT NOT NULL AUTO_INCREMENT,
  `NamaAcara` VARCHAR(45) NULL,
  `TemaKegiatan` VARCHAR(45) NULL,
  `TanggalKegiatan` VARCHAR(45) NULL,
  `Acaracol` DATE NULL,
  `Kuota` INT NULL,
  `Gambar` VARCHAR(50) NULL,
  PRIMARY KEY (`KodeAcara`));
ENGINE = INNODB;


-- -----------------------------------------------------
-- Table `E_tiketing`.`Tiket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `E_tiketing`.`Tiket` (
  `NIM` INT NOT NULL,
  `KodeAcara` INT NOT NULL,
  `NoKursi` INT NULL,
  `Mahasiswa_has_Acaracol` VARCHAR(45) NULL,
  PRIMARY KEY (`NIM`, `KodeAcara`),
  INDEX `fk_Mahasiswa_has_Acara_Acara1_idx` (`KodeAcara` ASC),
  INDEX `fk_Mahasiswa_has_Acara_Mahasiswa_idx` (`NIM` ASC),
  CONSTRAINT `fk_Mahasiswa_has_Acara_Mahasiswa`
    FOREIGN KEY (`NIM`)
    REFERENCES `E_tiketing`.`Mahasiswa` (`NIM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mahasiswa_has_Acara_Acara1`
    FOREIGN KEY (`KodeAcara`)
    REFERENCES `E_tiketing`.`Acara` (`KodeAcara`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
ENGINE = INNODB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
