CREATE DATABASE proyek_psw2;
USE proyek_psw2;

CREATE TABLE mahasiswa(
	NIM INT PRIMARY KEY,
	Nama VARCHAR(255) NOT NULL,
	Prodi VARCHAR(50) NOT NULL	
);

CREATE TABLE akun(
	Username VARCHAR(30) PRIMARY KEY,
	NIM INT NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	Role CHAR(2) CHECK(Role IN(1,2)),
	
	FOREIGN KEY (NIM) REFERENCES mahasiswa(NIM) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Acara(
	kode_acara CHAR(15) PRIMARY KEY,
	nama_kegiatan VARCHAR(50) NOT NULL,
	tema_kegiatan VARCHAR(50) NOT NULL,
	gambar VARCHAR(200) NOT NULL,
	tanggal_kegiatan DATE NOT NULL,
	jam_mulai TIME NOT NULL,
	lokasi VARCHAR(100) NOT NULL,
	kuota INT NOT NULL,
	deskripsi TEXT NOT NULL
);

CREATE TABLE tiket(
	No_tiket INT PRIMARY KEY AUTO_INCREMENT,
	NIM INT NOT NULL,
	kode_acara CHAR(15),
	no_kursi INT NOT NULL,
	
	FOREIGN KEY (NIM) REFERENCES mahasiswa(NIM) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (kode_acara) REFERENCES Acara(kode_acara) ON DELETE CASCADE ON UPDATE CASCADE
);
